name: airflow-docker (master)

on:
  push:
    branches:
      - master

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [airflow]
        python_version: [3.7]
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-python${{matrix.python_version}}
          --build-arg PYTHON_VERSION=${{matrix.python_version}}
          src/base
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-python${{matrix.python_version}}

  build-setup-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [airflow]
        python_version: [3.7]
        airflow_version: [1.10.10, 1.10.11]
    needs: build-base-image
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.airflow_version}}-python${{matrix.python_version}}
          --build-arg PYTHON_VERSION=${{matrix.python_version}}
          --build-arg AIRFLOW_VERSION=${{matrix.airflow_version}}
          src/setup
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.airflow_version}}-python${{matrix.python_version}}
